export {ProfileInfo} from './Profile-info'
export {ProfileStatus} from './Profile-status/Profile-status'
export {ProfilePhoto} from './Profile-photo/Profile-photo'
export {ProfileData} from './Profile-data/Profile-data'
export {ProfileDataForm} from './Profile-data-form/Profile-data-form'
export {Contacts} from './Contacts/Contacts'